! Automatically generated by cfwrapper.py on Wed Jun 22 23:34:35 2011
! Please do not modify.
! This file is part of the gtk-fortran GTK+ Fortran Interface library.
! GNU General Public License version 3
enum, bind(c)    !GtkIconListMode
    enumerator :: GTK_ICON_LIST_ICON
    enumerator :: GTK_ICON_LIST_TEXT_RIGHT
    enumerator :: GTK_ICON_LIST_TEXT_BELOW
end enum
enum, bind(c)    !GtkPlotCanvasPlotPos
    enumerator :: GTK_PLOT_CANVAS_PLOT_OUT
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_PLOT
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_LEGENDS
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_TITLE
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_AXIS
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_DATA
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_GRADIENT
    enumerator :: GTK_PLOT_CANVAS_PLOT_IN_MARKER
end enum
enum, bind(c)    !GtkPlotScale
    enumerator :: GTK_PLOT_SCALE_LINEAR 
    enumerator :: GTK_PLOT_SCALE_LOG10 
end enum
 
enum, bind(c)    !GtkPlotSymbolType
    enumerator :: GTK_PLOT_SYMBOL_NONE 
    enumerator :: GTK_PLOT_SYMBOL_SQUARE 
    enumerator :: GTK_PLOT_SYMBOL_CIRCLE 
    enumerator :: GTK_PLOT_SYMBOL_UP_TRIANGLE 
    enumerator :: GTK_PLOT_SYMBOL_DOWN_TRIANGLE 
    enumerator :: GTK_PLOT_SYMBOL_RIGHT_TRIANGLE 
    enumerator :: GTK_PLOT_SYMBOL_LEFT_TRIANGLE 
    enumerator :: GTK_PLOT_SYMBOL_DIAMOND 
    enumerator :: GTK_PLOT_SYMBOL_PLUS 
    enumerator :: GTK_PLOT_SYMBOL_CROSS 
    enumerator :: GTK_PLOT_SYMBOL_STAR 
    enumerator :: GTK_PLOT_SYMBOL_DOT 
    enumerator :: GTK_PLOT_SYMBOL_IMPULSE 
end enum
 
enum, bind(c)    !GtkPlotSymbolStyle
    enumerator :: GTK_PLOT_SYMBOL_EMPTY 
    enumerator :: GTK_PLOT_SYMBOL_FILLED 
    enumerator :: GTK_PLOT_SYMBOL_OPAQUE 
end enum
 
enum, bind(c)    !GtkPlotBorderStyle
    enumerator :: GTK_PLOT_BORDER_NONE 
    enumerator :: GTK_PLOT_BORDER_LINE 
    enumerator :: GTK_PLOT_BORDER_SHADOW 
end enum
 
enum, bind(c)    !GtkPlotLineStyle
    enumerator :: GTK_PLOT_LINE_NONE 
    enumerator :: GTK_PLOT_LINE_SOLID 
    enumerator :: GTK_PLOT_LINE_DOTTED 
    enumerator :: GTK_PLOT_LINE_DASHED 
    enumerator :: GTK_PLOT_LINE_DOT_DASH 
    enumerator :: GTK_PLOT_LINE_DOT_DOT_DASH 
    enumerator :: GTK_PLOT_LINE_DOT_DASH_DASH 
end enum
 
enum, bind(c)    !GtkPlotConnector
    enumerator :: GTK_PLOT_CONNECT_NONE 
    enumerator :: GTK_PLOT_CONNECT_STRAIGHT 
    enumerator :: GTK_PLOT_CONNECT_SPLINE 
    enumerator :: GTK_PLOT_CONNECT_HV_STEP 
    enumerator :: GTK_PLOT_CONNECT_VH_STEP 
    enumerator :: GTK_PLOT_CONNECT_MIDDLE_STEP 
end enum
 
enum, bind(c)    !GtkPlotLabelPos
    enumerator :: GTK_PLOT_LABEL_NONE = 0
    enumerator :: GTK_PLOT_LABEL_IN = b'1'
    enumerator :: GTK_PLOT_LABEL_OUT = b'10'
end enum
 
enum, bind(c)    !GtkPlotError
    enumerator :: GTK_PLOT_ERROR_DIV_ZERO
    enumerator :: GTK_PLOT_ERROR_LOG_NEG
end enum
 
enum, bind(c)    !GtkPlotOrientation
    enumerator :: GTK_PLOT_AXIS_X 
    enumerator :: GTK_PLOT_AXIS_Y 
    enumerator :: GTK_PLOT_AXIS_Z 
end enum
 
enum, bind(c)    !GtkPlotAxisPos
    enumerator :: GTK_PLOT_AXIS_LEFT 
    enumerator :: GTK_PLOT_AXIS_RIGHT 
    enumerator :: GTK_PLOT_AXIS_TOP 
    enumerator :: GTK_PLOT_AXIS_BOTTOM 
end enum
 
enum, bind(c)    !GtkPlotLabelStyle
    enumerator :: GTK_PLOT_LABEL_FLOAT 
    enumerator :: GTK_PLOT_LABEL_EXP 
    enumerator :: GTK_PLOT_LABEL_POW 
end enum
 
enum, bind(c)    !GtkPlotTicksPos
    enumerator :: GTK_PLOT_TICKS_NONE = 0
    enumerator :: GTK_PLOT_TICKS_IN = b'1'
    enumerator :: GTK_PLOT_TICKS_OUT = b'10'
end enum
enum, bind(c)    !GtkPlotPageSize
    enumerator :: GTK_PLOT_LETTER 
    enumerator :: GTK_PLOT_LEGAL 
    enumerator :: GTK_PLOT_A4 
    enumerator :: GTK_PLOT_EXECUTIVE 
    enumerator :: GTK_PLOT_CUSTOM 
end enum
 
enum, bind(c)    !GtkPlotPageOrientation
    enumerator :: GTK_PLOT_PORTRAIT 
    enumerator :: GTK_PLOT_LANDSCAPE 
end enum
 
enum, bind(c)    !GtkPlotUnits
    enumerator :: GTK_PLOT_PSPOINTS 
    enumerator :: GTK_PLOT_MM 
    enumerator :: GTK_PLOT_CM 
    enumerator :: GTK_PLOT_INCHES 
end enum
enum, bind(c)    !GtkPlotCanvasAction
    enumerator :: GTK_PLOT_CANVAS_ACTION_INACTIVE
    enumerator :: GTK_PLOT_CANVAS_ACTION_SELECTION
    enumerator :: GTK_PLOT_CANVAS_ACTION_DRAG
    enumerator :: GTK_PLOT_CANVAS_ACTION_RESIZE
end enum
 
enum, bind(c)    !GtkPlotCanvasFlag
    enumerator :: GTK_PLOT_CANVAS_FROZEN = 0
    enumerator :: GTK_PLOT_CANVAS_CAN_MOVE = b'1'
    enumerator :: GTK_PLOT_CANVAS_CAN_RESIZE = b'10'
end enum
 
enum, bind(c)    !GtkPlotCanvasSelection
    enumerator :: GTK_PLOT_CANVAS_SELECT_NONE 
    enumerator :: GTK_PLOT_CANVAS_SELECT_MARKERS
    enumerator :: GTK_PLOT_CANVAS_SELECT_TARGET
end enum
 
enum, bind(c)    !GtkPlotCanvasSelectionMode
    enumerator :: GTK_PLOT_CANVAS_SELECT_CLICK_1 
    enumerator :: GTK_PLOT_CANVAS_SELECT_CLICK_2
end enum
 
enum, bind(c)    !GtkPlotCanvasPos
    enumerator :: GTK_PLOT_CANVAS_OUT
    enumerator :: GTK_PLOT_CANVAS_IN
    enumerator :: GTK_PLOT_CANVAS_LEFT
    enumerator :: GTK_PLOT_CANVAS_RIGHT
    enumerator :: GTK_PLOT_CANVAS_TOP
    enumerator :: GTK_PLOT_CANVAS_BOTTOM
    enumerator :: GTK_PLOT_CANVAS_TOP_LEFT
    enumerator :: GTK_PLOT_CANVAS_TOP_RIGHT
    enumerator :: GTK_PLOT_CANVAS_BOTTOM_LEFT
    enumerator :: GTK_PLOT_CANVAS_BOTTOM_RIGHT
end enum
enum, bind(c)    !GtkPlotArrow
    enumerator :: GTK_PLOT_ARROW_NONE = 0
    enumerator :: GTK_PLOT_ARROW_ORIGIN = b'1'
    enumerator :: GTK_PLOT_ARROW_END = b'10'
end enum
enum, bind(c)    !GtkPlotPlane
    enumerator :: GTK_PLOT_PLANE_XY = 0
    enumerator :: GTK_PLOT_PLANE_YX = 0
    enumerator :: GTK_PLOT_PLANE_XZ = 1
    enumerator :: GTK_PLOT_PLANE_ZX = 1
    enumerator :: GTK_PLOT_PLANE_YZ = 2
    enumerator :: GTK_PLOT_PLANE_ZY = 2
end enum
 
enum, bind(c)    !GtkPlotSide
    enumerator :: GTK_PLOT_SIDE_XY = b'1' 
    enumerator :: GTK_PLOT_SIDE_XZ = b'10' 
    enumerator :: GTK_PLOT_SIDE_YX = b'100' 
    enumerator :: GTK_PLOT_SIDE_YZ = b'1000' 
    enumerator :: GTK_PLOT_SIDE_ZX = b'10000' 
    enumerator :: GTK_PLOT_SIDE_ZY = b'100000' 
end enum
enum, bind(c)    !GtkPlotBarUnits
    enumerator :: GTK_PLOT_BAR_POINTS
    enumerator :: GTK_PLOT_BAR_RELATIVE
    enumerator :: GTK_PLOT_BAR_ABSOLUTE
end enum
enum, bind(c)    !GtkPlotProjection
    enumerator :: GTK_PLOT_PROJECT_NONE 
    enumerator :: GTK_PLOT_PROJECT_EMPTY 
    enumerator :: GTK_PLOT_PROJECT_FULL 
end enum
enum, bind(c)    !GtkPlotCanvasArrow
    enumerator :: GTK_PLOT_CANVAS_ARROW_NONE = 0
    enumerator :: GTK_PLOT_CANVAS_ARROW_ORIGIN = b'1'
    enumerator :: GTK_PLOT_CANVAS_ARROW_END = b'10'
end enum
