! Automatically generated by cfwrapper.py on Sat Feb 16 17:36:00 2013
! Please do not modify.
! This file is part of the gtk-fortran GTK+ Fortran Interface library.
! GNU General Public License version 3

module gdk_pixbuf
implicit none
interface

!   GType gdk_pixbuf_simple_anim_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_simple_anim_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_simple_anim_get_type
end function

! GType gdk_pixbuf_simple_anim_iter_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_simple_anim_iter_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_simple_anim_iter_get_type
end function

!  GdkPixbufSimpleAnim *gdk_pixbuf_simple_anim_new (gint width, gint height, gfloat rate);
function gdk_pixbuf_simple_anim_new(width, height, rate) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_float
  type(c_ptr) :: gdk_pixbuf_simple_anim_new
  integer(c_int), value :: width
  integer(c_int), value :: height
  real(c_float), value :: rate
end function

! void gdk_pixbuf_simple_anim_add_frame (GdkPixbufSimpleAnim *animation, GdkPixbuf *pixbuf);
subroutine gdk_pixbuf_simple_anim_add_frame(animation, pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: animation
  type(c_ptr), value :: pixbuf
end subroutine

! void gdk_pixbuf_simple_anim_set_loop (GdkPixbufSimpleAnim *animation, gboolean loop);
subroutine gdk_pixbuf_simple_anim_set_loop(animation, loop) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: animation
  integer(c_int), value :: loop
end subroutine

! gboolean gdk_pixbuf_simple_anim_get_loop (GdkPixbufSimpleAnim *animation);
function gdk_pixbuf_simple_anim_get_loop(animation) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_simple_anim_get_loop
  type(c_ptr), value :: animation
end function

!   guint8* gdk_pixdata_serialize (const GdkPixdata *pixdata, guint *stream_length_p);
function gdk_pixdata_serialize(pixdata, stream_length_p) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixdata_serialize
  type(c_ptr), value :: pixdata
  type(c_ptr), value :: stream_length_p
end function

! gboolean gdk_pixdata_deserialize (GdkPixdata *pixdata, guint stream_length, const guint8 *stream, GError **error);
function gdk_pixdata_deserialize(pixdata, stream_length, stream, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixdata_deserialize
  type(c_ptr), value :: pixdata
  integer(c_int), value :: stream_length
  type(c_ptr), value :: stream
  type(c_ptr), value :: error
end function

! gpointer gdk_pixdata_from_pixbuf (GdkPixdata *pixdata, const GdkPixbuf *pixbuf, gboolean use_rle);
function gdk_pixdata_from_pixbuf(pixdata, pixbuf, use_rle) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixdata_from_pixbuf
  type(c_ptr), value :: pixdata
  type(c_ptr), value :: pixbuf
  integer(c_int), value :: use_rle
end function

! GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata, gboolean copy_pixels, GError **error);
function gdk_pixbuf_from_pixdata(pixdata, copy_pixels, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_from_pixdata
  type(c_ptr), value :: pixdata
  integer(c_int), value :: copy_pixels
  type(c_ptr), value :: error
end function

!    GString* gdk_pixdata_to_csource (GdkPixdata *pixdata, const gchar *name, GdkPixdataDumpType dump_type);
function gdk_pixdata_to_csource(pixdata, name, dump_type) bind(c) 
  use iso_c_binding, only: c_ptr, c_char, c_int
  type(c_ptr) :: gdk_pixdata_to_csource
  type(c_ptr), value :: pixdata
  character(kind=c_char), dimension(*) :: name
  integer(c_int), value :: dump_type
end function

!   GQuark gdk_pixbuf_error_quark (void);
function gdk_pixbuf_error_quark() bind(c) 
  use iso_c_binding, only: c_int32_t
  integer(c_int32_t) :: gdk_pixbuf_error_quark
end function

!    GType gdk_pixbuf_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_get_type
end function

!  GdkPixbuf *gdk_pixbuf_ref (GdkPixbuf *pixbuf);
function gdk_pixbuf_ref(pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_ref
  type(c_ptr), value :: pixbuf
end function

!  void gdk_pixbuf_unref (GdkPixbuf *pixbuf);
subroutine gdk_pixbuf_unref(pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: pixbuf
end subroutine

!  GdkColorspace gdk_pixbuf_get_colorspace (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_colorspace(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_colorspace
  type(c_ptr), value :: pixbuf
end function

! int gdk_pixbuf_get_n_channels (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_n_channels(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_n_channels
  type(c_ptr), value :: pixbuf
end function

! gboolean gdk_pixbuf_get_has_alpha (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_has_alpha(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_has_alpha
  type(c_ptr), value :: pixbuf
end function

! int gdk_pixbuf_get_bits_per_sample (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_bits_per_sample(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_bits_per_sample
  type(c_ptr), value :: pixbuf
end function

! guchar *gdk_pixbuf_get_pixels (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_pixels(pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_get_pixels
  type(c_ptr), value :: pixbuf
end function

! int gdk_pixbuf_get_width (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_width(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_width
  type(c_ptr), value :: pixbuf
end function

! int gdk_pixbuf_get_height (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_height(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_height
  type(c_ptr), value :: pixbuf
end function

! int gdk_pixbuf_get_rowstride (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_rowstride(pixbuf) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_get_rowstride
  type(c_ptr), value :: pixbuf
end function

! gsize gdk_pixbuf_get_byte_length (const GdkPixbuf *pixbuf);
function gdk_pixbuf_get_byte_length(pixbuf) bind(c) 
  use iso_c_binding, only: c_size_t, c_ptr
  integer(c_size_t) :: gdk_pixbuf_get_byte_length
  type(c_ptr), value :: pixbuf
end function

!  guchar *gdk_pixbuf_get_pixels_with_length (const GdkPixbuf *pixbuf, guint *length);
function gdk_pixbuf_get_pixels_with_length(pixbuf, length) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_get_pixels_with_length
  type(c_ptr), value :: pixbuf
  type(c_ptr), value :: length
end function

!    GdkPixbuf *gdk_pixbuf_new (GdkColorspace colorspace, gboolean has_alpha, int bits_per_sample, int width, int height);
function gdk_pixbuf_new(colorspace, has_alpha, bits_per_sample, width, height) &
&bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_new
  integer(c_int), value :: colorspace
  integer(c_int), value :: has_alpha
  integer(c_int), value :: bits_per_sample
  integer(c_int), value :: width
  integer(c_int), value :: height
end function

!  GdkPixbuf *gdk_pixbuf_copy (const GdkPixbuf *pixbuf);
function gdk_pixbuf_copy(pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_copy
  type(c_ptr), value :: pixbuf
end function

!  GdkPixbuf *gdk_pixbuf_new_subpixbuf (GdkPixbuf *src_pixbuf, int src_x, int src_y, int width, int height);
function gdk_pixbuf_new_subpixbuf(src_pixbuf, src_x, src_y, width, height) bind&
&(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_new_subpixbuf
  type(c_ptr), value :: src_pixbuf
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: width
  integer(c_int), value :: height
end function

!  GdkPixbuf *gdk_pixbuf_new_from_file (const char *filename, GError **error);
function gdk_pixbuf_new_from_file(filename, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_new_from_file
  character(kind=c_char), dimension(*) :: filename
  type(c_ptr), value :: error
end function

! GdkPixbuf *gdk_pixbuf_new_from_file_at_size (const char *filename, int width, int height, GError **error);
function gdk_pixbuf_new_from_file_at_size(filename, width, height, error) bind(&
&c) 
  use iso_c_binding, only: c_ptr, c_char, c_int
  type(c_ptr) :: gdk_pixbuf_new_from_file_at_size
  character(kind=c_char), dimension(*) :: filename
  integer(c_int), value :: width
  integer(c_int), value :: height
  type(c_ptr), value :: error
end function

! GdkPixbuf *gdk_pixbuf_new_from_file_at_scale (const char *filename, int width, int height, gboolean preserve_aspect_ratio, GError **error);
function gdk_pixbuf_new_from_file_at_scale(filename, width, height, preserve_as&
&pect_ratio, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char, c_int
  type(c_ptr) :: gdk_pixbuf_new_from_file_at_scale
  character(kind=c_char), dimension(*) :: filename
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: preserve_aspect_ratio
  type(c_ptr), value :: error
end function

! GdkPixbuf *gdk_pixbuf_new_from_resource (const char *resource_path, GError **error);
function gdk_pixbuf_new_from_resource(resource_path, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_new_from_resource
  character(kind=c_char), dimension(*) :: resource_path
  type(c_ptr), value :: error
end function

! GdkPixbuf *gdk_pixbuf_new_from_resource_at_scale (const char *resource_path, int width, int height, gboolean preserve_aspect_ratio, GError **error);
function gdk_pixbuf_new_from_resource_at_scale(resource_path, width, height, pr&
&eserve_aspect_ratio, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char, c_int
  type(c_ptr) :: gdk_pixbuf_new_from_resource_at_scale
  character(kind=c_char), dimension(*) :: resource_path
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: preserve_aspect_ratio
  type(c_ptr), value :: error
end function

!  GdkPixbuf *gdk_pixbuf_new_from_data (const guchar *data, GdkColorspace colorspace, gboolean has_alpha, int bits_per_sample, int width, int height, int rowstride, GdkPixbufDestroyNotify destroy_fn, gpointer destroy_fn_data);
function gdk_pixbuf_new_from_data(data, colorspace, has_alpha, bits_per_sample,&
& width, height, rowstride, destroy_fn, destroy_fn_data) bind(c) 
  use iso_c_binding, only: c_ptr, c_char, c_int, c_funptr
  type(c_ptr) :: gdk_pixbuf_new_from_data
  character(kind=c_char), dimension(*) :: data
  integer(c_int), value :: colorspace
  integer(c_int), value :: has_alpha
  integer(c_int), value :: bits_per_sample
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: rowstride
  type(c_funptr), value :: destroy_fn
  type(c_ptr), value :: destroy_fn_data
end function

!  GdkPixbuf *gdk_pixbuf_new_from_xpm_data (const char **data);
function gdk_pixbuf_new_from_xpm_data(data) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_new_from_xpm_data
  type(c_ptr), dimension(*) :: data
end function

! GdkPixbuf* gdk_pixbuf_new_from_inline (gint data_length, const guint8 *data, gboolean copy_pixels, GError **error);
function gdk_pixbuf_new_from_inline(data_length, data, copy_pixels, error) bind&
&(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_new_from_inline
  integer(c_int), value :: data_length
  type(c_ptr), value :: data
  integer(c_int), value :: copy_pixels
  type(c_ptr), value :: error
end function

!   void gdk_pixbuf_fill (GdkPixbuf *pixbuf, guint32 pixel);
subroutine gdk_pixbuf_fill(pixbuf, pixel) bind(c) 
  use iso_c_binding, only: c_ptr, c_int32_t
  type(c_ptr), value :: pixbuf
  integer(c_int32_t), value :: pixel
end subroutine

!  gboolean gdk_pixbuf_savev (GdkPixbuf *pixbuf, const char *filename, const char *type, char **option_keys, char **option_values, GError **error);
function gdk_pixbuf_savev(pixbuf, filename, type, option_keys, option_values, e&
&rror) bind(c) 
  use iso_c_binding, only: c_int, c_ptr, c_char
  integer(c_int) :: gdk_pixbuf_savev
  type(c_ptr), value :: pixbuf
  character(kind=c_char), dimension(*) :: filename
  character(kind=c_char), dimension(*) :: type
  type(c_ptr), dimension(*) :: option_keys
  type(c_ptr), dimension(*) :: option_values
  type(c_ptr), value :: error
end function

!  gboolean gdk_pixbuf_save_to_callbackv (GdkPixbuf *pixbuf, GdkPixbufSaveFunc save_func, gpointer user_data, const char *type, char **option_keys, char **option_values, GError **error);
function gdk_pixbuf_save_to_callbackv(pixbuf, save_func, user_data, type, optio&
&n_keys, option_values, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr, c_funptr, c_char
  integer(c_int) :: gdk_pixbuf_save_to_callbackv
  type(c_ptr), value :: pixbuf
  type(c_funptr), value :: save_func
  type(c_ptr), value :: user_data
  character(kind=c_char), dimension(*) :: type
  type(c_ptr), dimension(*) :: option_keys
  type(c_ptr), dimension(*) :: option_values
  type(c_ptr), value :: error
end function

!  gboolean gdk_pixbuf_save_to_bufferv (GdkPixbuf *pixbuf, gchar **buffer, gsize *buffer_size, const char *type, char **option_keys, char **option_values, GError **error);
function gdk_pixbuf_save_to_bufferv(pixbuf, buffer, buffer_size, type, option_k&
&eys, option_values, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr, c_char
  integer(c_int) :: gdk_pixbuf_save_to_bufferv
  type(c_ptr), value :: pixbuf
  type(c_ptr), dimension(*) :: buffer
  type(c_ptr), value :: buffer_size
  character(kind=c_char), dimension(*) :: type
  type(c_ptr), dimension(*) :: option_keys
  type(c_ptr), dimension(*) :: option_values
  type(c_ptr), value :: error
end function

!  GdkPixbuf *gdk_pixbuf_new_from_stream (GInputStream *stream, GCancellable *cancellable, GError **error);
function gdk_pixbuf_new_from_stream(stream, cancellable, error) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_new_from_stream
  type(c_ptr), value :: stream
  type(c_ptr), value :: cancellable
  type(c_ptr), value :: error
end function

!  void gdk_pixbuf_new_from_stream_async (GInputStream *stream, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data);
subroutine gdk_pixbuf_new_from_stream_async(stream, cancellable, callback, user&
&_data) bind(c) 
  use iso_c_binding, only: c_ptr, c_funptr
  type(c_ptr), value :: stream
  type(c_ptr), value :: cancellable
  type(c_funptr), value :: callback
  type(c_ptr), value :: user_data
end subroutine

!  GdkPixbuf *gdk_pixbuf_new_from_stream_finish (GAsyncResult *async_result, GError **error);
function gdk_pixbuf_new_from_stream_finish(async_result, error) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_new_from_stream_finish
  type(c_ptr), value :: async_result
  type(c_ptr), value :: error
end function

!  GdkPixbuf *gdk_pixbuf_new_from_stream_at_scale (GInputStream *stream, gint width, gint height, gboolean preserve_aspect_ratio, GCancellable *cancellable, GError **error);
function gdk_pixbuf_new_from_stream_at_scale(stream, width, height, preserve_as&
&pect_ratio, cancellable, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_new_from_stream_at_scale
  type(c_ptr), value :: stream
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: preserve_aspect_ratio
  type(c_ptr), value :: cancellable
  type(c_ptr), value :: error
end function

!  void gdk_pixbuf_new_from_stream_at_scale_async (GInputStream *stream, gint width, gint height, gboolean preserve_aspect_ratio, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data);
subroutine gdk_pixbuf_new_from_stream_at_scale_async(stream, width, height, pre&
&serve_aspect_ratio, cancellable, callback, user_data) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_funptr
  type(c_ptr), value :: stream
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: preserve_aspect_ratio
  type(c_ptr), value :: cancellable
  type(c_funptr), value :: callback
  type(c_ptr), value :: user_data
end subroutine

!  gboolean gdk_pixbuf_save_to_stream_finish (GAsyncResult *async_result, GError **error);
function gdk_pixbuf_save_to_stream_finish(async_result, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_save_to_stream_finish
  type(c_ptr), value :: async_result
  type(c_ptr), value :: error
end function

!  GdkPixbuf *gdk_pixbuf_add_alpha (const GdkPixbuf *pixbuf, gboolean substitute_color, guchar r, guchar g, guchar b);
function gdk_pixbuf_add_alpha(pixbuf, substitute_color, r, g, b) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_int8_t
  type(c_ptr) :: gdk_pixbuf_add_alpha
  type(c_ptr), value :: pixbuf
  integer(c_int), value :: substitute_color
  integer(kind=c_int8_t), value :: r
  integer(kind=c_int8_t), value :: g
  integer(kind=c_int8_t), value :: b
end function

!  void gdk_pixbuf_copy_area (const GdkPixbuf *src_pixbuf, int src_x, int src_y, int width, int height, GdkPixbuf *dest_pixbuf, int dest_x, int dest_y);
subroutine gdk_pixbuf_copy_area(src_pixbuf, src_x, src_y, width, height, dest_p&
&ixbuf, dest_x, dest_y) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: src_pixbuf
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: width
  integer(c_int), value :: height
  type(c_ptr), value :: dest_pixbuf
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
end subroutine

!  void gdk_pixbuf_saturate_and_pixelate (const GdkPixbuf *src, GdkPixbuf *dest, gfloat saturation, gboolean pixelate);
subroutine gdk_pixbuf_saturate_and_pixelate(src, dest, saturation, pixelate) bi&
&nd(c) 
  use iso_c_binding, only: c_ptr, c_float, c_int
  type(c_ptr), value :: src
  type(c_ptr), value :: dest
  real(c_float), value :: saturation
  integer(c_int), value :: pixelate
end subroutine

!  GdkPixbuf *gdk_pixbuf_apply_embedded_orientation (GdkPixbuf *src);
function gdk_pixbuf_apply_embedded_orientation(src) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_apply_embedded_orientation
  type(c_ptr), value :: src
end function

!  const gchar * gdk_pixbuf_get_option (GdkPixbuf *pixbuf, const gchar *key);
function gdk_pixbuf_get_option(pixbuf, key) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_get_option
  type(c_ptr), value :: pixbuf
  character(kind=c_char), dimension(*) :: key
end function

!   GType gdk_pixbuf_animation_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_animation_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_animation_get_type
end function

!  GdkPixbufAnimation *gdk_pixbuf_animation_new_from_file (const char *filename, GError **error);
function gdk_pixbuf_animation_new_from_file(filename, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_animation_new_from_file
  character(kind=c_char), dimension(*) :: filename
  type(c_ptr), value :: error
end function

!  GdkPixbufAnimation *gdk_pixbuf_animation_ref (GdkPixbufAnimation *animation);
function gdk_pixbuf_animation_ref(animation) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_animation_ref
  type(c_ptr), value :: animation
end function

!  void gdk_pixbuf_animation_unref (GdkPixbufAnimation *animation);
subroutine gdk_pixbuf_animation_unref(animation) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: animation
end subroutine

!  int gdk_pixbuf_animation_get_width (GdkPixbufAnimation *animation);
function gdk_pixbuf_animation_get_width(animation) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_get_width
  type(c_ptr), value :: animation
end function

! int gdk_pixbuf_animation_get_height (GdkPixbufAnimation *animation);
function gdk_pixbuf_animation_get_height(animation) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_get_height
  type(c_ptr), value :: animation
end function

! gboolean gdk_pixbuf_animation_is_static_image (GdkPixbufAnimation *animation);
function gdk_pixbuf_animation_is_static_image(animation) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_is_static_image
  type(c_ptr), value :: animation
end function

! GdkPixbuf *gdk_pixbuf_animation_get_static_image (GdkPixbufAnimation *animation);
function gdk_pixbuf_animation_get_static_image(animation) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_animation_get_static_image
  type(c_ptr), value :: animation
end function

!  GdkPixbufAnimationIter *gdk_pixbuf_animation_get_iter (GdkPixbufAnimation *animation, const GTimeVal *start_time);
function gdk_pixbuf_animation_get_iter(animation, start_time) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_animation_get_iter
  type(c_ptr), value :: animation
  type(c_ptr), value :: start_time
end function

! GType gdk_pixbuf_animation_iter_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_animation_iter_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_animation_iter_get_type
end function

! int gdk_pixbuf_animation_iter_get_delay_time (GdkPixbufAnimationIter *iter);
function gdk_pixbuf_animation_iter_get_delay_time(iter) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_iter_get_delay_time
  type(c_ptr), value :: iter
end function

! GdkPixbuf *gdk_pixbuf_animation_iter_get_pixbuf (GdkPixbufAnimationIter *iter);
function gdk_pixbuf_animation_iter_get_pixbuf(iter) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_animation_iter_get_pixbuf
  type(c_ptr), value :: iter
end function

! gboolean gdk_pixbuf_animation_iter_on_currently_loading_frame (GdkPixbufAnimationIter *iter);
function gdk_pixbuf_animation_iter_on_currently_loading_frame(iter) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_iter_on_currently_loading_frame
  type(c_ptr), value :: iter
end function

! gboolean gdk_pixbuf_animation_iter_advance (GdkPixbufAnimationIter *iter, const GTimeVal *current_time);
function gdk_pixbuf_animation_iter_advance(iter, current_time) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_animation_iter_advance
  type(c_ptr), value :: iter
  type(c_ptr), value :: current_time
end function

!        GType gdk_pixbuf_non_anim_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_non_anim_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_non_anim_get_type
end function

! GdkPixbufAnimation* gdk_pixbuf_non_anim_new (GdkPixbuf *pixbuf);
function gdk_pixbuf_non_anim_new(pixbuf) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_non_anim_new
  type(c_ptr), value :: pixbuf
end function

!   GType gdk_pixbuf_loader_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_loader_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_loader_get_type
end function

! GdkPixbufLoader * gdk_pixbuf_loader_new (void);
function gdk_pixbuf_loader_new() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_loader_new
end function

! GdkPixbufLoader * gdk_pixbuf_loader_new_with_type (const char *image_type, GError **error);
function gdk_pixbuf_loader_new_with_type(image_type, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_loader_new_with_type
  character(kind=c_char), dimension(*) :: image_type
  type(c_ptr), value :: error
end function

! GdkPixbufLoader * gdk_pixbuf_loader_new_with_mime_type (const char *mime_type, GError **error);
function gdk_pixbuf_loader_new_with_mime_type(mime_type, error) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_loader_new_with_mime_type
  character(kind=c_char), dimension(*) :: mime_type
  type(c_ptr), value :: error
end function

! void gdk_pixbuf_loader_set_size (GdkPixbufLoader *loader, int width, int height);
subroutine gdk_pixbuf_loader_set_size(loader, width, height) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: loader
  integer(c_int), value :: width
  integer(c_int), value :: height
end subroutine

! gboolean gdk_pixbuf_loader_write (GdkPixbufLoader *loader, const guchar *buf, gsize count, GError **error);
function gdk_pixbuf_loader_write(loader, buf, count, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr, c_char, c_size_t
  integer(c_int) :: gdk_pixbuf_loader_write
  type(c_ptr), value :: loader
  character(kind=c_char), dimension(*) :: buf
  integer(c_size_t), value :: count
  type(c_ptr), value :: error
end function

! GdkPixbuf * gdk_pixbuf_loader_get_pixbuf (GdkPixbufLoader *loader);
function gdk_pixbuf_loader_get_pixbuf(loader) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_loader_get_pixbuf
  type(c_ptr), value :: loader
end function

! GdkPixbufAnimation * gdk_pixbuf_loader_get_animation (GdkPixbufLoader *loader);
function gdk_pixbuf_loader_get_animation(loader) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_loader_get_animation
  type(c_ptr), value :: loader
end function

! gboolean gdk_pixbuf_loader_close (GdkPixbufLoader *loader, GError **error);
function gdk_pixbuf_loader_close(loader, error) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_loader_close
  type(c_ptr), value :: loader
  type(c_ptr), value :: error
end function

! GdkPixbufFormat *gdk_pixbuf_loader_get_format (GdkPixbufLoader *loader);
function gdk_pixbuf_loader_get_format(loader) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_loader_get_format
  type(c_ptr), value :: loader
end function

!   GType gdk_pixbuf_alpha_mode_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_alpha_mode_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_alpha_mode_get_type
end function

!  GType gdk_colorspace_get_type (void) G_GNUC_CONST;
function gdk_colorspace_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_colorspace_get_type
end function

!  GType gdk_pixbuf_error_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_error_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_error_get_type
end function

!  GType gdk_interp_type_get_type (void) G_GNUC_CONST;
function gdk_interp_type_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_interp_type_get_type
end function

!  GType gdk_pixbuf_rotation_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_rotation_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_rotation_get_type
end function

!    GType gdk_pixbuf_format_get_type (void) G_GNUC_CONST;
function gdk_pixbuf_format_get_type() bind(c) 
  use iso_c_binding, only: c_size_t
  integer(c_size_t) :: gdk_pixbuf_format_get_type
end function

!  GSList *gdk_pixbuf_get_formats (void);
function gdk_pixbuf_get_formats() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_get_formats
end function

! gchar *gdk_pixbuf_format_get_name (GdkPixbufFormat *format);
function gdk_pixbuf_format_get_name(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_get_name
  type(c_ptr), value :: format
end function

! gchar *gdk_pixbuf_format_get_description (GdkPixbufFormat *format);
function gdk_pixbuf_format_get_description(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_get_description
  type(c_ptr), value :: format
end function

! gchar **gdk_pixbuf_format_get_mime_types (GdkPixbufFormat *format);
function gdk_pixbuf_format_get_mime_types(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_get_mime_types
  type(c_ptr), value :: format
end function

! gchar **gdk_pixbuf_format_get_extensions (GdkPixbufFormat *format);
function gdk_pixbuf_format_get_extensions(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_get_extensions
  type(c_ptr), value :: format
end function

! gboolean gdk_pixbuf_format_is_writable (GdkPixbufFormat *format);
function gdk_pixbuf_format_is_writable(format) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_format_is_writable
  type(c_ptr), value :: format
end function

! gboolean gdk_pixbuf_format_is_scalable (GdkPixbufFormat *format);
function gdk_pixbuf_format_is_scalable(format) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_format_is_scalable
  type(c_ptr), value :: format
end function

! gboolean gdk_pixbuf_format_is_disabled (GdkPixbufFormat *format);
function gdk_pixbuf_format_is_disabled(format) bind(c) 
  use iso_c_binding, only: c_int, c_ptr
  integer(c_int) :: gdk_pixbuf_format_is_disabled
  type(c_ptr), value :: format
end function

! void gdk_pixbuf_format_set_disabled (GdkPixbufFormat *format, gboolean disabled);
subroutine gdk_pixbuf_format_set_disabled(format, disabled) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: format
  integer(c_int), value :: disabled
end subroutine

! gchar *gdk_pixbuf_format_get_license (GdkPixbufFormat *format);
function gdk_pixbuf_format_get_license(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_get_license
  type(c_ptr), value :: format
end function

!  GdkPixbufFormat *gdk_pixbuf_get_file_info (const gchar *filename, gint *width, gint *height);
function gdk_pixbuf_get_file_info(filename, width, height) bind(c) 
  use iso_c_binding, only: c_ptr, c_char
  type(c_ptr) :: gdk_pixbuf_get_file_info
  character(kind=c_char), dimension(*) :: filename
  type(c_ptr), value :: width
  type(c_ptr), value :: height
end function

!  GdkPixbufFormat *gdk_pixbuf_format_copy (const GdkPixbufFormat *format);
function gdk_pixbuf_format_copy(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: gdk_pixbuf_format_copy
  type(c_ptr), value :: format
end function

! void gdk_pixbuf_format_free (GdkPixbufFormat *format);
subroutine gdk_pixbuf_format_free(format) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: format
end subroutine

!    gboolean gdk_pixbuf_set_option (GdkPixbuf *pixbuf, const gchar *key, const gchar *value);
function gdk_pixbuf_set_option(pixbuf, key, value) bind(c) 
  use iso_c_binding, only: c_int, c_ptr, c_char
  integer(c_int) :: gdk_pixbuf_set_option
  type(c_ptr), value :: pixbuf
  character(kind=c_char), dimension(*) :: key
  character(kind=c_char), dimension(*) :: value
end function

!   void gdk_pixbuf_scale (const GdkPixbuf *src, GdkPixbuf *dest, int dest_x, int dest_y, int dest_width, int dest_height, double offset_x, double offset_y, double scale_x, double scale_y, GdkInterpType interp_type);
subroutine gdk_pixbuf_scale(src, dest, dest_x, dest_y, dest_width, dest_height,&
& offset_x, offset_y, scale_x, scale_y, interp_type) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_double
  type(c_ptr), value :: src
  type(c_ptr), value :: dest
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: dest_width
  integer(c_int), value :: dest_height
  real(c_double), value :: offset_x
  real(c_double), value :: offset_y
  real(c_double), value :: scale_x
  real(c_double), value :: scale_y
  integer(c_int), value :: interp_type
end subroutine

! void gdk_pixbuf_composite (const GdkPixbuf *src, GdkPixbuf *dest, int dest_x, int dest_y, int dest_width, int dest_height, double offset_x, double offset_y, double scale_x, double scale_y, GdkInterpType interp_type, int overall_alpha);
subroutine gdk_pixbuf_composite(src, dest, dest_x, dest_y, dest_width, dest_hei&
&ght, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_double
  type(c_ptr), value :: src
  type(c_ptr), value :: dest
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: dest_width
  integer(c_int), value :: dest_height
  real(c_double), value :: offset_x
  real(c_double), value :: offset_y
  real(c_double), value :: scale_x
  real(c_double), value :: scale_y
  integer(c_int), value :: interp_type
  integer(c_int), value :: overall_alpha
end subroutine

! void gdk_pixbuf_composite_color (const GdkPixbuf *src, GdkPixbuf *dest, int dest_x, int dest_y, int dest_width, int dest_height, double offset_x, double offset_y, double scale_x, double scale_y, GdkInterpType interp_type, int overall_alpha, int check_x, int check_y, int check_size, guint32 color1, guint32 color2);
subroutine gdk_pixbuf_composite_color(src, dest, dest_x, dest_y, dest_width, de&
&st_height, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha, c&
&heck_x, check_y, check_size, color1, color2) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_double, c_int32_t
  type(c_ptr), value :: src
  type(c_ptr), value :: dest
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: dest_width
  integer(c_int), value :: dest_height
  real(c_double), value :: offset_x
  real(c_double), value :: offset_y
  real(c_double), value :: scale_x
  real(c_double), value :: scale_y
  integer(c_int), value :: interp_type
  integer(c_int), value :: overall_alpha
  integer(c_int), value :: check_x
  integer(c_int), value :: check_y
  integer(c_int), value :: check_size
  integer(c_int32_t), value :: color1
  integer(c_int32_t), value :: color2
end subroutine

!  GdkPixbuf *gdk_pixbuf_scale_simple (const GdkPixbuf *src, int dest_width, int dest_height, GdkInterpType interp_type);
function gdk_pixbuf_scale_simple(src, dest_width, dest_height, interp_type) bin&
&d(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_scale_simple
  type(c_ptr), value :: src
  integer(c_int), value :: dest_width
  integer(c_int), value :: dest_height
  integer(c_int), value :: interp_type
end function

!  GdkPixbuf *gdk_pixbuf_composite_color_simple (const GdkPixbuf *src, int dest_width, int dest_height, GdkInterpType interp_type, int overall_alpha, int check_size, guint32 color1, guint32 color2);
function gdk_pixbuf_composite_color_simple(src, dest_width, dest_height, interp&
&_type, overall_alpha, check_size, color1, color2) bind(c) 
  use iso_c_binding, only: c_ptr, c_int, c_int32_t
  type(c_ptr) :: gdk_pixbuf_composite_color_simple
  type(c_ptr), value :: src
  integer(c_int), value :: dest_width
  integer(c_int), value :: dest_height
  integer(c_int), value :: interp_type
  integer(c_int), value :: overall_alpha
  integer(c_int), value :: check_size
  integer(c_int32_t), value :: color1
  integer(c_int32_t), value :: color2
end function

!  GdkPixbuf *gdk_pixbuf_rotate_simple (const GdkPixbuf *src, GdkPixbufRotation angle);
function gdk_pixbuf_rotate_simple(src, angle) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_rotate_simple
  type(c_ptr), value :: src
  integer(c_int), value :: angle
end function

! GdkPixbuf *gdk_pixbuf_flip (const GdkPixbuf *src, gboolean horizontal);
function gdk_pixbuf_flip(src, horizontal) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: gdk_pixbuf_flip
  type(c_ptr), value :: src
  integer(c_int), value :: horizontal
end function

!     void gdk_pixbuf_xlib_init (Display *display, int screen_num);
subroutine gdk_pixbuf_xlib_init(display, screen_num) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: display
  integer(c_int), value :: screen_num
end subroutine

!  void gdk_pixbuf_xlib_init_with_depth (Display *display, int screen_num, int prefDepth);
subroutine gdk_pixbuf_xlib_init_with_depth(display, screen_num, prefDepth) bind&
&(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: display
  integer(c_int), value :: screen_num
  integer(c_int), value :: prefDepth
end subroutine

!    void gdk_pixbuf_xlib_render_threshold_alpha (GdkPixbuf *pixbuf, Pixmap bitmap, int src_x, int src_y, int dest_x, int dest_y, int width, int height, int alpha_threshold);
subroutine gdk_pixbuf_xlib_render_threshold_alpha(pixbuf, bitmap, src_x, src_y,&
& dest_x, dest_y, width, height, alpha_threshold) bind(c) 
  use iso_c_binding, only: c_ptr, c_long, c_int
  type(c_ptr), value :: pixbuf
  integer(c_long), value :: bitmap
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: alpha_threshold
end subroutine

!  void gdk_pixbuf_xlib_render_to_drawable (GdkPixbuf *pixbuf, Drawable drawable, GC gc, int src_x, int src_y, int dest_x, int dest_y, int width, int height, XlibRgbDither dither, int x_dither, int y_dither);
subroutine gdk_pixbuf_xlib_render_to_drawable(pixbuf, drawable, gc, src_x, src_&
&y, dest_x, dest_y, width, height, dither, x_dither, y_dither) bind(c) 
  use iso_c_binding, only: c_ptr, c_long, c_int
  type(c_ptr), value :: pixbuf
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dither
  integer(c_int), value :: x_dither
  integer(c_int), value :: y_dither
end subroutine

!  void gdk_pixbuf_xlib_render_to_drawable_alpha (GdkPixbuf *pixbuf, Drawable drawable, int src_x, int src_y, int dest_x, int dest_y, int width, int height, GdkPixbufAlphaMode alpha_mode, int alpha_threshold, XlibRgbDither dither, int x_dither, int y_dither);
subroutine gdk_pixbuf_xlib_render_to_drawable_alpha(pixbuf, drawable, src_x, sr&
&c_y, dest_x, dest_y, width, height, alpha_mode, alpha_threshold, dither, x_dit&
&her, y_dither) bind(c) 
  use iso_c_binding, only: c_ptr, c_long, c_int
  type(c_ptr), value :: pixbuf
  integer(c_long), value :: drawable
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: alpha_mode
  integer(c_int), value :: alpha_threshold
  integer(c_int), value :: dither
  integer(c_int), value :: x_dither
  integer(c_int), value :: y_dither
end subroutine

!  void gdk_pixbuf_xlib_render_pixmap_and_mask (GdkPixbuf *pixbuf, Pixmap *pixmap_return, Pixmap *mask_return, int alpha_threshold);
subroutine gdk_pixbuf_xlib_render_pixmap_and_mask(pixbuf, pixmap_return, mask_r&
&eturn, alpha_threshold) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: pixbuf
  type(c_ptr), value :: pixmap_return
  type(c_ptr), value :: mask_return
  integer(c_int), value :: alpha_threshold
end subroutine

!    GdkPixbuf *gdk_pixbuf_xlib_get_from_drawable (GdkPixbuf *dest, Drawable src, Colormap cmap, Visual *visual, int src_x, int src_y, int dest_x, int dest_y, int width, int height);
function gdk_pixbuf_xlib_get_from_drawable(dest, src, cmap, visual, src_x, src_&
&y, dest_x, dest_y, width, height) bind(c) 
  use iso_c_binding, only: c_ptr, c_long, c_int
  type(c_ptr) :: gdk_pixbuf_xlib_get_from_drawable
  type(c_ptr), value :: dest
  integer(c_long), value :: src
  integer(c_long), value :: cmap
  type(c_ptr), value :: visual
  integer(c_int), value :: src_x
  integer(c_int), value :: src_y
  integer(c_int), value :: dest_x
  integer(c_int), value :: dest_y
  integer(c_int), value :: width
  integer(c_int), value :: height
end function

!   void xlib_rgb_init (Display *display, Screen *screen);
subroutine xlib_rgb_init(display, screen) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: display
  type(c_ptr), value :: screen
end subroutine

! void xlib_rgb_init_with_depth (Display *display, Screen *screen, int prefDepth);
subroutine xlib_rgb_init_with_depth(display, screen, prefDepth) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr), value :: display
  type(c_ptr), value :: screen
  integer(c_int), value :: prefDepth
end subroutine

!  unsigned long xlib_rgb_xpixel_from_rgb (guint32 rgb);
function xlib_rgb_xpixel_from_rgb(rgb) bind(c) 
  use iso_c_binding, only: c_long, c_int32_t
  integer(c_long) :: xlib_rgb_xpixel_from_rgb
  integer(c_int32_t), value :: rgb
end function

!  void xlib_rgb_gc_set_foreground (GC gc, guint32 rgb);
subroutine xlib_rgb_gc_set_foreground(gc, rgb) bind(c) 
  use iso_c_binding, only: c_ptr, c_int32_t
  type(c_ptr), value :: gc
  integer(c_int32_t), value :: rgb
end subroutine

!  void xlib_rgb_gc_set_background (GC gc, guint32 rgb);
subroutine xlib_rgb_gc_set_background(gc, rgb) bind(c) 
  use iso_c_binding, only: c_ptr, c_int32_t
  type(c_ptr), value :: gc
  integer(c_int32_t), value :: rgb
end subroutine

!  void xlib_draw_rgb_image (Drawable drawable, GC gc, int x, int y, int width, int height, XlibRgbDither dith, unsigned char *rgb_buf, int rowstride);
subroutine xlib_draw_rgb_image(drawable, gc, x, y, width, height, dith, rgb_buf&
&, rowstride) bind(c) 
  use iso_c_binding, only: c_long, c_ptr, c_int
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: x
  integer(c_int), value :: y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dith
  type(c_ptr), value :: rgb_buf
  integer(c_int), value :: rowstride
end subroutine

!  void xlib_draw_rgb_image_dithalign (Drawable drawable, GC gc, int x, int y, int width, int height, XlibRgbDither dith, unsigned char *rgb_buf, int rowstride, int xdith, int ydith);
subroutine xlib_draw_rgb_image_dithalign(drawable, gc, x, y, width, height, dit&
&h, rgb_buf, rowstride, xdith, ydith) bind(c) 
  use iso_c_binding, only: c_long, c_ptr, c_int
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: x
  integer(c_int), value :: y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dith
  type(c_ptr), value :: rgb_buf
  integer(c_int), value :: rowstride
  integer(c_int), value :: xdith
  integer(c_int), value :: ydith
end subroutine

!  void xlib_draw_rgb_32_image (Drawable drawable, GC gc, int x, int y, int width, int height, XlibRgbDither dith, unsigned char *buf, int rowstride);
subroutine xlib_draw_rgb_32_image(drawable, gc, x, y, width, height, dith, buf,&
& rowstride) bind(c) 
  use iso_c_binding, only: c_long, c_ptr, c_int
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: x
  integer(c_int), value :: y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dith
  type(c_ptr), value :: buf
  integer(c_int), value :: rowstride
end subroutine

!  void xlib_draw_gray_image (Drawable drawable, GC gc, int x, int y, int width, int height, XlibRgbDither dith, unsigned char *buf, int rowstride);
subroutine xlib_draw_gray_image(drawable, gc, x, y, width, height, dith, buf, r&
&owstride) bind(c) 
  use iso_c_binding, only: c_long, c_ptr, c_int
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: x
  integer(c_int), value :: y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dith
  type(c_ptr), value :: buf
  integer(c_int), value :: rowstride
end subroutine

!  XlibRgbCmap * xlib_rgb_cmap_new (guint32 *colors, int n_colors);
function xlib_rgb_cmap_new(colors, n_colors) bind(c) 
  use iso_c_binding, only: c_ptr, c_int
  type(c_ptr) :: xlib_rgb_cmap_new
  type(c_ptr), value :: colors
  integer(c_int), value :: n_colors
end function

!  void xlib_rgb_cmap_free (XlibRgbCmap *cmap);
subroutine xlib_rgb_cmap_free(cmap) bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr), value :: cmap
end subroutine

!  void xlib_draw_indexed_image (Drawable drawable, GC gc, int x, int y, int width, int height, XlibRgbDither dith, unsigned char *buf, int rowstride, XlibRgbCmap *cmap);
subroutine xlib_draw_indexed_image(drawable, gc, x, y, width, height, dith, buf&
&, rowstride, cmap) bind(c) 
  use iso_c_binding, only: c_long, c_ptr, c_int
  integer(c_long), value :: drawable
  type(c_ptr), value :: gc
  integer(c_int), value :: x
  integer(c_int), value :: y
  integer(c_int), value :: width
  integer(c_int), value :: height
  integer(c_int), value :: dith
  type(c_ptr), value :: buf
  integer(c_int), value :: rowstride
  type(c_ptr), value :: cmap
end subroutine

!  Bool xlib_rgb_ditherable (void);
function xlib_rgb_ditherable() bind(c) 
  use iso_c_binding, only: c_int
  integer(c_int) :: xlib_rgb_ditherable
end function

!  void xlib_rgb_set_verbose (Bool verbose);
subroutine xlib_rgb_set_verbose(verbose) bind(c) 
  use iso_c_binding, only: c_int
  integer(c_int), value :: verbose
end subroutine

!  void xlib_rgb_set_install (Bool install);
subroutine xlib_rgb_set_install(install) bind(c) 
  use iso_c_binding, only: c_int
  integer(c_int), value :: install
end subroutine

!  void xlib_rgb_set_min_colors (int min_colors);
subroutine xlib_rgb_set_min_colors(min_colors) bind(c) 
  use iso_c_binding, only: c_int
  integer(c_int), value :: min_colors
end subroutine

!  Colormap xlib_rgb_get_cmap (void);
function xlib_rgb_get_cmap() bind(c) 
  use iso_c_binding, only: c_long
  integer(c_long) :: xlib_rgb_get_cmap
end function

!  Visual * xlib_rgb_get_visual (void);
function xlib_rgb_get_visual() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: xlib_rgb_get_visual
end function

!  XVisualInfo * xlib_rgb_get_visual_info (void);
function xlib_rgb_get_visual_info() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: xlib_rgb_get_visual_info
end function

!  int xlib_rgb_get_depth (void);
function xlib_rgb_get_depth() bind(c) 
  use iso_c_binding, only: c_int
  integer(c_int) :: xlib_rgb_get_depth
end function

!  Display * xlib_rgb_get_display (void);
function xlib_rgb_get_display() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: xlib_rgb_get_display
end function

!  Screen * xlib_rgb_get_screen (void);
function xlib_rgb_get_screen() bind(c) 
  use iso_c_binding, only: c_ptr
  type(c_ptr) :: xlib_rgb_get_screen
end function

end interface
end module gdk_pixbuf
